services:
  flask-app:
    image: rdn51015/flask-app:latest
    ports:
      - 8000:80
    volumes:
      - .:/app
      - /app/__pycache__/
    environment:
      - PYTHONUNBUFFERED=1            # Forces real-time log printing in your terminal
    healthcheck:
      test: ["CMD","curl",-f","http://localhost:80/health"]
      interval: 10s
      timeout: 5s
      retries: 3